---
spring:
  profiles: eurekaone
server:
  port: 8761
eureka:
  instance:
    hostname: eurekaone
  client:
    service-url:
      default-zone: http://eurekatwo:8761/eureka

---
spring:
  profiles: eurekatwo
server:
  port: 8761
eureka:
  instance:
    hostname: eurekatwo
  client:
    service-url:
      default-zone: http://eurekaone:8761/eureka